services:
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: grupo_gad_db_prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
      - ./docker/init_postgis.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      # No exponer el puerto de la BD a la red host en producción
      # La comunicación es a través de la red interna de Docker.
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - grupo_gad_net_prod

  redis:
    image: redis:7-alpine
    container_name: grupo_gad_redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data_prod:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - grupo_gad_net_prod

  api:
    image: ghcr.io/eevans-d/grupo_gad/api:v1.0.0
    container_name: grupo_gad_api_prod
    volumes: [] # Eliminar los montajes de volumen para usar el código dentro de la imagen
    ports:
      # No exponer el puerto de la API directamente; Caddy es el punto de entrada
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - grupo_gad_net_prod

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    container_name: grupo_gad_bot_prod
    volumes: [] # Eliminar montajes de volumen
    env_file:
      - .env.production
    restart: always
    depends_on:
      api:
        condition: service_healthy
    networks:
      - grupo_gad_net_prod

  caddy:
    image: caddy:2.8
    container_name: grupo_gad_caddy_prod
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data_prod:/data
      - caddy_config_prod:/config
    depends_on:
      api:
        condition: service_healthy
    networks:
      - grupo_gad_net_prod

networks:
  grupo_gad_net_prod:
    driver: bridge

volumes:
  postgres_data_prod:
  redis_data_prod:
  caddy_data_prod:
  caddy_config_prod:
