services:
  db:
    image: postgis/postgis:15-3.4-alpine
    container_name: grupo_gad_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/init_postgis.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - gad_network

  redis:
    image: redis:7-alpine
    container_name: grupo_gad_redis
    command: 
      - redis-server
      - --appendonly
      - "yes"
      - --requirepass
      - ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - gad_network

  api:
    image: ghcr.io/eevans-d/grupo_gad/api:v1.0.0
    container_name: grupo_gad_api
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gad_network

  bot:
    image: ghcr.io/eevans-d/grupo_gad/bot:v1.0.0
    container_name: grupo_gad_bot
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    depends_on:
      api:
        condition: service_healthy
    networks:
      - gad_network

  caddy:
    image: caddy:2.8
    container_name: grupo_gad_caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    depends_on:
      api:
        condition: service_healthy
    networks:
      - gad_network

networks:
  gad_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
  caddy_data:
  caddy_config:
