version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-pass}
      POSTGRES_DB: gad
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - gad-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d gad"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # The volume mount is kept for development to allow live reloading
    volumes:
      - ./api:/app
    environment:
      - DB_URL=${DB_URL}
    ports:
      - "8000:8000" # Expose port 8000 to the host to access the dashboard
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gad-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=http://api:8000/api/v1
      - WHITELIST_IDS=${WHITELIST_IDS}
    depends_on:
      api:
        condition: service_healthy
    networks:
      - gad-net

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"  # UI local para config
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=pass
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_CONNECTION_STRING=${DB_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    volumes:
      - n8n-data:/root/.n8n
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gad-net

networks:
  gad-net:
volumes:
  db-data:
  n8n-data: