# ========================================================================
# 🚨 AlertManager Configuration - GRUPO_GAD
# ========================================================================

global:
  # Tiempo que espera antes de enviar una alerta
  resolve_timeout: 5m
  
  # SMTP configuration (correo electrónico)
  smtp_from: 'alerts@grupogad.gob.ec'
  smtp_smarthost: 'smtp.gmail.com:587'  # O tu servidor SMTP
  smtp_auth_username: 'alerts@grupogad.gob.ec'
  smtp_auth_password: 'CAMBIAR_POR_PASSWORD_SMTP'
  smtp_require_tls: true

# Plantillas para notificaciones
templates:
  - '/etc/alertmanager/*.tmpl'

# ========================================================================
# Routes: Determina cómo se enrutan las alertas
# ========================================================================
route:
  # Receptor por defecto
  receiver: 'default-receiver'
  
  # Agrupar alertas por...
  group_by: ['alertname', 'component', 'severity']
  
  # Esperar 10s para agrupar alertas similares
  group_wait: 10s
  
  # Si llegan más alertas del mismo grupo, esperar 5m antes de notificar
  group_interval: 5m
  
  # Re-enviar alerta cada 4 horas si no se resuelve
  repeat_interval: 4h
  
  # Rutas específicas
  routes:
    # Alertas CRÍTICAS: Email + Slack inmediato
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h
    
    # Alertas WARNING: Solo Slack
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 4h
    
    # Alertas de Database: Email específico
    - match:
        component: database
      receiver: 'database-team'
    
    # Alertas de API: Email específico
    - match:
        component: api
      receiver: 'api-team'

# ========================================================================
# Receivers: Destinos de las alertas
# ========================================================================
receivers:
  # ======================================================================
  # Default: Email básico
  # ======================================================================
  - name: 'default-receiver'
    email_configs:
      - to: 'devops@grupogad.gob.ec'
        headers:
          Subject: '[GRUPO_GAD] {{ .GroupLabels.alertname }}'
        html: |
          <!DOCTYPE html>
          <html>
          <body>
            <h2>🚨 Alerta: {{ .GroupLabels.alertname }}</h2>
            <p><strong>Severity:</strong> {{ .GroupLabels.severity }}</p>
            <p><strong>Component:</strong> {{ .GroupLabels.component }}</p>
            <hr>
            {{ range .Alerts }}
            <h3>{{ .Labels.alertname }}</h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Summary:</strong> {{ .Annotations.summary }}</p>
            <p><strong>Started:</strong> {{ .StartsAt }}</p>
            <hr>
            {{ end }}
          </body>
          </html>
  
  # ======================================================================
  # Critical: Email + Slack
  # ======================================================================
  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@grupogad.gob.ec, cto@grupogad.gob.ec'
        headers:
          Subject: '🚨 [CRITICAL] {{ .GroupLabels.alertname }}'
    
    # Slack webhook (opcional)
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
        channel: '#alerts-critical'
        title: '🚨 CRITICAL ALERT'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .GroupLabels.severity }}
          *Component:* {{ .GroupLabels.component }}
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true
  
  # ======================================================================
  # Warning: Solo Slack
  # ======================================================================
  - name: 'warning-alerts'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/WEBHOOK/URL'
        channel: '#alerts-warning'
        title: '⚠️ WARNING'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Component:* {{ .GroupLabels.component }}
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}
        send_resolved: true
  
  # ======================================================================
  # Database Team
  # ======================================================================
  - name: 'database-team'
    email_configs:
      - to: 'database@grupogad.gob.ec'
        headers:
          Subject: '[DATABASE] {{ .GroupLabels.alertname }}'
  
  # ======================================================================
  # API Team
  # ======================================================================
  - name: 'api-team'
    email_configs:
      - to: 'api-team@grupogad.gob.ec'
        headers:
          Subject: '[API] {{ .GroupLabels.alertname }}'

# ========================================================================
# Inhibition Rules: Suprimir alertas redundantes
# ========================================================================
inhibit_rules:
  # Si API está DOWN, no notificar sobre high latency
  - source_match:
      severity: 'critical'
      alertname: 'APIDown'
    target_match:
      severity: 'warning'
      component: 'api'
    equal: ['instance']
  
  # Si servidor está DOWN, no notificar sobre servicios individuales
  - source_match:
      severity: 'critical'
      alertname: 'InstanceDown'
    target_match:
      severity: 'warning'
    equal: ['instance']
