version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: gad_db_prod
    restart: unless-stopped
    env_file:
      - ../.env.production
    environment:
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - gad-network-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: gad_redis_prod
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data_prod:/data
    networks:
      - gad-network-prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    image: ghcr.io/eevans-d/grupo_gad/api:v1.0.0
    container_name: gad_api_prod
    restart: unless-stopped
    env_file:
      - ../.env.production
    ports:
      - "127.0.0.1:8001:8000"  # puerto local distinto para evitar conflicto con dev
    volumes:
      - ../logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - gad-network-prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    container_name: gad_bot_prod
    restart: unless-stopped
    env_file:
      - ../.env.production
    depends_on:
      api:
        condition: service_started
    networks:
      - gad-network-prod

networks:
  gad-network-prod:
    driver: bridge

volumes:
  postgres_data_prod:
  redis_data_prod:
