name: Stability Health Check

on:
  schedule:
    - cron: '30 4 * * *'  # diario 04:30 UTC
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Type check (mypy)
        run: |
          poetry run mypy

      - name: Lint (ruff)
        run: |
          poetry run ruff check --output-format=github

      - name: Tests (pytest)
        run: |
          poetry run pytest -q

      - name: Summary
        if: always()
        run: |
          echo "Stability Check finished. See job logs for details."