name: Standard
on: [push, pull_request]
jobs:
  standard:
    runs-on: ubuntu-latest
    env:
      # Allow repository secret to supply DATABASE_URL for integration steps
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install Node deps
        if: hashFiles('package.json') != ''
        run: npm ci
      - name: Lint
        if: hashFiles('package.json') != ''
        run: npx eslint . || echo "Lint warnings"
      - name: Typecheck  
        if: hashFiles('package.json') != ''
        run: npx tsc --noEmit || echo "Type warnings"
      - name: Node tests
        if: hashFiles('package.json') != ''
        run: npm test --silent
        
      - name: Setup Python
        if: hashFiles('pyservice/requirements.txt') != ''
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Python deps
        if: hashFiles('pyservice/requirements.txt') != ''
        run: python -m pip install -r pyservice/requirements.txt
      - name: Python tests
        if: hashFiles('pyservice/tests/') != ''
        run: cd pyservice && pytest -q
        
      - name: Check allowlists
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/check_allowlist.py
        
      - name: Basic security scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit
